---
title: "Internet in Ohio"
author: "Y. Yu"
date: "5/17/2021"
---
output: github_document
          
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-",
  out.width = "100%"
)
```

## Tidytuesday 2020-05-11

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(sf)
library(maps)
library(tigris)
library(scales)
```

# Data Exploriation

```{r}
bb <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-11/broadband.csv')
bb_ohio <- bb %>% filter(ST == "OH")
head(bb_ohio)
dim(bb_ohio)
```

```{r}
bb_zip <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-11/broadband_zip.csv')
bb_zip_ohio <- bb_zip %>% filter(ST == "OH") 
head(bb_zip_ohio)
dim(bb_zip_ohio)
```
```{r, echo = T, results = 'hide'}
# code is referenced from https://github.com/andybridger/TidyTuesday/blob/main/2021w20/2021w20.R
substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}
OH_data <- filter(bb, ST == "OH")
OH_data$COUNTYFP <- substrRight(as.character(OH_data$`COUNTY ID`), 3)
tracts_max <- tracts(state = 'OH')
ggtract_OH<-fortify(tracts_max, region = "GEOID") 
ggtract_OH<-left_join(ggtract_OH, OH_data, by=c("COUNTYFP")) 
```


```{r, include = TRUE, fig.height = 6, fig.width = 15, fig.align = "center"}
# code is referenced from https://github.com/andybridger/TidyTuesday/blob/main/2021w20/2021w20.R
ggplot() +
  geom_sf(data = ggtract_OH, aes(fill=as.numeric(`BROADBAND AVAILABILITY PER FCC`)), colour = "#061541", size =0.25) +
  coord_sf(datum = NA)+
  scale_fill_viridis_c(limits=c(0,1), 
                       breaks=c(0,1, 0.5), labels=c("0", "100%", "50%"),
                       guide = guide_colourbar(title.position = "top"))+
  theme_minimal(base_size=10)+
  theme(plot.subtitle = element_text(size=9),
        plot.title=element_text(size=14))+
  guides(fill = guide_colorbar(title.position = "top",
                               title.hjust = 0.5,
                               reverse = FALSE,
                               barheight = unit(10,"lines"),
                               barwidth = unit(0.5, "lines")))+
  labs(fill="",
       title = "Ohio")
```


