---
title: "Data Wrangling and Visualization on Manager Survey"
author: "Y. Yu"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message= FALSE, warning= FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(knitr)
library(viridis)
```


# Data Exploration

```{r, message= FALSE, warning= FALSE}
survey <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')
head(survey)
dim(survey)
survey$highest_level_of_education_completed <- factor(survey$highest_level_of_education_completed, levels = c(
"High School", "Some college", "College degree", "Master's degree", "PhD", "Professional degree (MD, JD, etc.)", "NA" 
))
```

Let's focus on the U.S. only for the moment.

```{r}
survey_us <- survey %>%
  filter(country == "United States")
```


```{r, warning = FALSE}
missing_values <- data.frame(col = names(survey_us),missing_value=colSums(is.na(survey_us)))
rownames(missing_values) <- 1:nrow(missing_values)
ggplot(missing_values, aes(col, missing_value, color = col, fill = col)) +
  geom_col() +
  theme_bw() +
  theme(legend.position = "none") +
  ggtitle("Column-wise Missing Value in the U.S.") +
  xlab("") + ylab("missing value count") + 
  coord_flip() 
```

Since we are in the U.S., it would be interesting to see the average `annual_salary` in each state. As we can see from the following code, the dataset on the U.S. states is super messy and so many "states" do not make any sense.

```{r, include= FALSE}
unique(survey_us$state)

```


```{r}
survey_us %>% filter(str_detect(state, ", ", negate = TRUE)) %>% 
  group_by(state) %>%
  summarize(mean_salary = mean(annual_salary)) %>%
  ggplot(aes(state, mean_salary, fill = state)) +
  geom_col(width = 0.5) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.y = element_text(size = 7)) +
  xlab("") +
  ylab("Average Salary") +
  coord_flip()


```

Surprisingly, Alabama has the hightest average salary. 


```{r, message = FALSE}
survey_us$highest_level_of_education_completed <- factor(survey_us$highest_level_of_education_completed, levels = c(
"High School", "Some college", "College degree", "Master's degree", "PhD", "Professional degree (MD, JD, etc.)", "NA" 
))
survey_us %>% group_by(highest_level_of_education_completed, gender) %>%
  summarize(mean_salary = mean(annual_salary)) %>%
  ggplot(aes(highest_level_of_education_completed, mean_salary, fill = highest_level_of_education_completed)) +
  geom_col(width = 0.5) +
  facet_wrap(~gender) +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.y = element_text(size = 8),
        legend.title = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 8)) +
  scale_x_discrete(labels = c("HS", "SC", "Col", "Mas", "PhD", "Pro", "NA")) + 
  xlab("") +
  ylab("Average Salary") +
  ggtitle("Gender-Wise Average Salary in the U.S.")
```

```{r, message = FALSE}
survey_us %>% group_by(highest_level_of_education_completed, gender) %>%
  summarize(annual_salary) %>% filter(annual_salary <= 300000) %>%
  ggplot(aes(highest_level_of_education_completed, annual_salary, fill = highest_level_of_education_completed)) +
  geom_boxplot() +
  facet_wrap(~gender) +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.y = element_text(size = 7),
        legend.title = element_blank(),
        axis.ticks = element_blank()) +
  xlab("") +
  ylab("Average Salary")  +
  scale_x_discrete(labels = c("HS", "SC", "Col", "Mas", "PhD", "Pro", "NA")) 
```


```{r}
unique(survey$overall_years_of_professional_experience)
survey$overall_years_of_professional_experience <- factor(survey$overall_years_of_professional_experience, levels = c(
  "1 year or less", "2 - 4 years", "5-7 years", "8 - 10 years", "11 - 20 years", "21 - 30 years", "31 - 40 years", "41 years or more"))
```

```{r, message = FALSE}

p1 <- survey %>% group_by(overall_years_of_professional_experience, highest_level_of_education_completed) %>%
  summarize(salary = mean(annual_salary)/1000) %>%
  ggplot(aes(highest_level_of_education_completed, overall_years_of_professional_experience, fill = salary)) +
  geom_tile() +
  xlab("Highest Level Of Education") +
  ylab("Years Of Professional Experience")  +
  scale_x_discrete(labels = c("High School", "Some College", "College", "Master's", "PhD", "Professional", "NA"))+
  scale_fill_viridis(name = "Salary (*1000)") +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.y = element_text(size = 8,  angle = 30, face = "bold"),
        axis.text.x = element_text(size = 8, face = "bold"),
        axis.title.x = element_text(vjust=-1, face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(size = 10, face = "bold"),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 10)) +
  ggtitle("Average Salary On Working Experience & Education Combined")

p1
  
```


```{r, message = FALSE}
p2 <- survey %>% group_by(overall_years_of_professional_experience, highest_level_of_education_completed) %>%
  summarize(salary = mean(annual_salary)) %>%
  group_by(overall_years_of_professional_experience) %>%
  mutate(min_max = (salary - min(salary))/(max(salary)- min(salary))) %>%
  ggplot(aes(highest_level_of_education_completed, overall_years_of_professional_experience, fill = min_max)) +
  geom_tile() +
  xlab("") +
  ylab("Years Of Professional Experience")  +
  scale_x_discrete(labels = c("High School", "Some College", "College", "Master's", "PhD", "Professional", "NA"))+
  scale_fill_viridis(name = "Normalized Salary") +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.y = element_text(size = 8,  angle = 30, face = "bold"),
        axis.text.x = element_text(size = 8, face = "bold"),
        axis.title.x = element_text(vjust=-1, face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(size = 10, face = "bold"),
        axis.ticks = element_blank(),
        legend.text = element_text(size = 10),
        legend.title.align = 1) +
  ggtitle("Education-Wise Salary (Min-Max)")

p2 
```

```{r, message = FALSE, warning= FALSE}
top_5_industry <- survey %>%
  group_by(industry) %>%
  summarize(total_count=n()) %>%
  arrange(desc(total_count)) %>%
  top_n(5, total_count)

survey %>%
  inner_join(top_5_industry, by = "industry") %>%
  #filter(industry %in% as.vector(top_5_industry)) %>%
  group_by(industry,highest_level_of_education_completed, gender) %>%
  summarize(percentage = 100 * n()/total_count) %>%
  distinct() %>%
  arrange(desc(percentage)) %>%
  ggplot(aes(highest_level_of_education_completed, percentage, fill = industry)) +
  geom_bar(stat = "identity", position = "fill") + 
  facet_wrap(~gender) +
  theme_bw() +
  theme(axis.text = element_text(size = 8, face = "bold"),
        legend.title = element_blank(),
        axis.ticks = element_blank(),
        legend.position = c(0.845, 0.2),
        legend.text = element_text(size = 8),
        strip.text = element_text(size=8, face = "bold")) +
  scale_x_discrete(labels = c("HS", "SC", "Col", "Mas", "PhD", "Pro", "NA")) + 
  xlab("Highest Level Of Education Completed") +
  ylab("Percentage Of Education") +
  ggtitle("Gender-Wise Education Distribution In 5 Most Popular Industries")
```


```{r, message=FALSE, warning=FALSE}
survey %>% group_by(gender, how_old_are_you, highest_level_of_education_completed) %>%
  summarize(count = n()) %>%
  arrange(desc(count)) %>%
  filter(count > 100) %>%
  ungroup() %>%
  ggplot(aes(gender, count, fill = highest_level_of_education_completed)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~how_old_are_you, scale = "free") + 
  coord_flip() +
  theme_classic() +
  theme(
    legend.position = c(0.85, 0.2),
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    axis.ticks = element_blank(),
    axis.text = element_text(size = 9),
    axis.title = element_text(size = 11)
  ) +
  labs(x = "Age", y = "Count") 
  
```

```{r, message = FALSE, warning= FALSE}
survey %>% 
  filter(currency == "USD") %>%
  group_by(city) %>%
  summarize(gender, norm_salary = annual_salary/1000, highest_level_of_education_completed) %>%
  arrange(desc(norm_salary)) %>%
  filter(norm_salary < 1000) %>%
  ggplot(aes(highest_level_of_education_completed, norm_salary, fill = highest_level_of_education_completed)) +
  geom_violin() +
  ylab("Annual Salary (USD) * 1000") + 
  coord_flip(clip = "off", expand = FALSE) +
  #facet_wrap(~gender) +
  theme_bw() +
  theme(
    legend.position = "top",
    axis.title.y = element_blank(),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(angle = 30, face = "bold"),
    legend.title = element_text(size = 12),
    axis.text.x = element_text(size = 12, face = "bold")
  ) +
  guides(fill = guide_legend(title = "Highest Degree Achieved", title.position = "top",
                             title.theme = element_text(size = 10, face = "bold"))) 

#ggsave("voilin plot.png", width = 20, height = 10)
```


```{r}
survey %>% count(race, sort = T)
```

```{r}
survey %>% filter(race != "NA") %>%
  separate(race, c("race", "extra"), sep = "or") %>%
  #select(race) %>% distinct()
  separate(race, c("race", "extra"), sep = ",") %>%
  select(race) %>%
  distinct()
```
```{r}
race_summary <- survey %>% 
    filter(race != "NA" & currency == "USD") %>%
    separate(race, c("race", "extra"), sep = "or") %>%
    separate(race, c("race", "extra"), sep = ",") 

race_summary <- race_summary %>% mutate(race = replace(race, race == "Another option not listed here", "Others"))

race_summary <- race_summary %>% mutate(race = ifelse(race == "Another option not listed here ", "Others", race))

race_summary <- race_summary %>%
  mutate(gender_update = case_when(
    gender %in% c("Woman")  ~ "Women",
    gender %in% c("Man")  ~ "Man",
    gender %in% c("Other or prefer not to answer", "Non-binary", "Prefer not to answer")  ~ "Others",
    is.na(gender) ~ "Others"
  ))

race_summary %>% count(race, sort = T)
```
```{r, message = FALSE}
race_summary %>% group_by(race, gender_update, highest_level_of_education_completed) %>%
  summarize(salary = mean(annual_salary), race, highest_level_of_education_completed) %>%
  distinct() %>%
  ggplot(aes(gender_update, salary, fill = highest_level_of_education_completed)) +
  #scale_y_log10() + 
  geom_bar(stat = "identity", position = "dodge") +
  #geom_boxplot() +
  facet_wrap(~race, scales = "free") +
  theme_bw() +
  theme(
    legend.position = c(0.6, 0.1),
    legend.text = element_text(size = 15),
    #strip.text = element_text(size=25, face = "bold"),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 15, face = "bold"),
    axis.title = element_text(size = 25, face= "bold"),
    legend.title = element_text(size = 12),
    axis.text.x = element_text(size = 12, face = "bold")
  ) +
  guides(fill = guide_legend(title = "Highest Degree Achieved", title.position = "top",
                             title.theme = element_text(size = 15, face = "bold"),
                             )) +
  labs(x = "", y = "Average Salary (USD)")

#ggsave("race plot.png", width = 20, height = 10)

```
```{r, message = FALSE}
race_summary$highest_level_of_education_completed <- recode(race_summary$highest_level_of_education_completed, `Professional degree (MD, JD, etc.)` = "Professional")
race_summary %>% filter(!is.na(highest_level_of_education_completed)) %>%
  group_by(race, highest_level_of_education_completed, gender_update) %>%
  summarize(count = n()) %>%
  ggplot(aes(gender_update, count, fill = highest_level_of_education_completed)) +
  geom_bar(stat = "identity", position = "dodge") +
  #geom_boxplot() +
  facet_wrap(~race, scales = "free") +
  theme_bw() +
  theme(
    legend.position = c(0.65, 0.1),
    legend.text = element_text(size = 10),
    strip.text = element_text(size=15, face = "bold"),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 15, face = "bold"),
    axis.title = element_text(size = 15, face= "bold"),
    legend.title = element_text(size = 12),
    axis.text.x = element_text(size = 12, face = "bold")
  ) +
  guides(fill = guide_legend(title = "Highest Degree Achieved", title.position = "left",
                             title.theme = element_text(size = 10, face = "bold"),
                             )) +
  labs(x = "", y = "Count of People")

ggsave("race_wise.png", width = 20, height = 10)

```


```{r}
race_summary %>% filter(!is.na(highest_level_of_education_completed)) %>%
  group_by(race, highest_level_of_education_completed, gender_update) %>%
  summarize(count = n()) %>%
  ggplot(aes(gender_update, count, fill = race)) +
  geom_bar(stat = "identity", position = "dodge") +
  #geom_boxplot() +
  facet_wrap(~highest_level_of_education_completed, scales = "free") +
  theme_bw() +
  theme(
    legend.position = "top",
    legend.text = element_text(size = 10),
    #strip.text = element_text(size=15, face = "bold"),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 15, face = "bold"),
    axis.title = element_text(size = 15, face= "bold"),
    legend.title = element_text(size = 12),
    axis.text.x = element_text(size = 12, face = "bold")
  ) +
  guides(fill = guide_legend(title = "", title.position = "left",
                             title.theme = element_text(size = 10, face = "bold"),
                             )) +
  labs(x = "", y = "Count of People")
ggsave("education_wise.png", width = 20, height = 10)
```

